function Export13File(app)

%--------------------------------------------------------------------------
% Check mesh attributes
%--------------------------------------------------------------------------
app.ProgressBarButton.Text = 'Checking mesh attributes...'; drawnow;

if ~isfield(app.MESH,'Attributes')
    msg = 'No attributes are found.';
    uiconfirm(app.UIFigure,msg,'ADMESH',...
        'Options',{'OK'},'DefaultOption',1,'Icon','Error');

    return;
end

Att = app.MESH.Attributes;
FieldNames = fields(Att);
numAtt = length(FieldNames);

%--------------------------------------------------------------------------
% Preallocate variables
%--------------------------------------------------------------------------
AttNames = cell(numAtt,1);
AttDefaultVals = nan(numAtt,1);
AttNonDefaultID = cell(numAtt,1);
AttNonDefaultVals = cell(numAtt,1);

%--------------------------------------------------------------------------
% Get attributes in fort.13 format
%--------------------------------------------------------------------------
for i = 1 : numAtt
    AttVals = Att.(FieldNames{i});

    switch lower(FieldNames{i})
        case 'manningn'
            AttNames{i} = 'mannings_n_at_sea_floor';
            AttDefaultVals(i) = mode(AttVals);
            AttNonDefaultID{i} = find(AttVals ~= AttDefaultVals(i));
            AttNonDefaultVals{i} = AttVals(AttNonDefaultID{i});
        case 'manningn_edge'
            AttID = AttVals(:,1);
            AttVals = AttVals(:,2);
            AttNames{i} = 'mannings_n_edge';
            AttDefaultVals(i) = mode(AttVals);
            AttNonDefaultID{i} = find(AttVals ~= AttDefaultVals(i));
            AttNonDefaultVals{i} = AttVals(AttNonDefaultID{i});

            AttNonDefaultID{i} = AttID(AttNonDefaultID{i}); % Convert to global node id
        otherwise
            msg = 'Wrong attributes are found. Abort exporting .13 file.';
            uiconfirm(app.UIFigure,msg,'ADMESH',...
                'Options',{'OK'},'DefaultOption',1,'Icon','Error');

    end
end

%--------------------------------------------------------------------------
% Select a file to save
%--------------------------------------------------------------------------
app.ProgressBarButton.Text = 'Writing .13 file...'; drawnow;

[file, path] = uiputfile(...
    {'*.13','Files (*.13)'},'Select a file to save attributes.');

if ~file
    return;
end

%--------------------------------------------------------------------------
% Open file and begin writing
%--------------------------------------------------------------------------
fid = fopen([path,file],'w');

%--------------------------------------------------------------------------
% Write grid name
%--------------------------------------------------------------------------
if isfield(app.MESH,'MeshID')
MeshID = app.MESH.MeshID;
if contains(MeshID,' - Generated by ADmesh')
    MeshID = MeshID(1:end-22);
end
else
    MeshID = '';
end
Grid_Name = inputdlg('Enter a grid name for your mesh file:', 'ADmesh', [1 50],{MeshID});

fprintf(fid,'%s\n',[Grid_Name{:}, ' - Generated by ADmesh']);

NP = size(app.MESH.Points,1);
fprintf(fid,'%d\n',NP);
fprintf(fid,'%d\n',numAtt);

%--------------------------------------------------------------------------
% Write attribute name, unit, and default values
%--------------------------------------------------------------------------
for i = 1 : numAtt
    fprintf(fid,'%s\n',AttNames{i});
    switch lower(AttNames{i})
        case 'mannings_n_at_sea_floor'
            fprintf(fid,'non\n');
            fprintf(fid,'1\n');
            fprintf(fid,'%g\n',AttDefaultVals(i));

        case 'mannings_n_edge'
            fprintf(fid,'non\n');
            fprintf(fid,'1\n');
            fprintf(fid,'%g\n',AttDefaultVals(i));
    end

end

%--------------------------------------------------------------------------
% Write non-default values
%--------------------------------------------------------------------------
for i = 1 : numAtt
    fprintf(fid,'%s\n',AttNames{i});
    fprintf(fid,'%d\n',length(AttNonDefaultID{i}));
    fprintf(fid,'%d %f\n',[AttNonDefaultID{i},AttNonDefaultVals{i}]');
end

fclose(fid);
app.ProgressBarButton.Text = 'Ready'; drawnow;




